#!/usr/bin/env bash
# vim: set ft=sh:

ARGS="$@"

if [ -z "$ARGS" ] ; then
  ARGS='web/themes/custom'
fi

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPT_DIR/.."

./node_modules/.bin/eslint --ignore-pattern '*.yml' --ignore-pattern '/**/dist/*' --fix --color $ARGS
