#!/usr/bin/env bash
# vim: set ft=sh:

ARGS="$@"

if [ -z "$ARGS" ] ; then
  ARGS='web/themes/custom/**/**/*.scss'
fi

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPT_DIR/.."

./node_modules/.bin/stylelint --color --fix $ARGS
